-- ============================================================================
--  DRAFT import of costings from Tenn_MindHome_EE_TFM_ALC Status.xlsx
--  Total Costing is imported as a single line (so Gross Profit = Selling - Cost
--  is exact); each row gets a 50% P.Sharing line. REVIEW against the workbook
--  before relying on it, then expand the cost breakdown per row as needed.
--  Boss-only table; run in the SQL Editor (service role bypasses RLS).
-- ============================================================================

insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/012','reno','AG15-WAYNE — 2 Room Premium',23444,'[{"label": "Total Costing", "amount": 15232.58}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/013','reno','AG16-WAYNE — 2 Room Premium',23444,'[{"label": "Total Costing", "amount": 14953.31}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/203','reno','A-03-02-TSL — 2 Room Customize',29999,'[{"label": "Total Costing", "amount": 11188.1}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/134','reno','A-08-10-WAYNE — 2 Room Customize',1199,'[{"label": "Total Costing", "amount": 968.53}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/202','reno','A-10-01-GES — 2 Room Customize',10238,'[{"label": "Total Costing", "amount": 5914.07}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/061','reno','D-02-32-CHAI — 2 Room Standard',19999,'[{"label": "Total Costing", "amount": 11263.53}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/123','reno','A-08-32-WAYNE — 2 Room Premium (excl 旋转桌)',21499,'[{"label": "Total Costing", "amount": 14240.96}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/194','reno','B-12-08-CHAI — 3 Room Premium add-on 厨房吊柜',30699,'[{"label": "Total Costing", "amount": 13873.41}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','A-09-15 BCY — Black Dry Kitchen Cabinet set',9599,'[{"label": "Total Costing", "amount": 4858.92}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','B-03-07 WAYNE — 3 Room Premium 餐边柜→厨房吊柜',29999,'[{"label": "Total Costing", "amount": 1000.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','C-03-09 BILLY — 3 Room Premium',36999,'[{"label": "Total Costing", "amount": 1000.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','C-05-02 CZX — 3 Room Premium',29999,'[{"label": "Total Costing", "amount": 1160.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','E-12-05-GES — 3 Room Premium (cabinet changes)',29999,'[{"label": "Total Costing", "amount": 1039.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','D-G-16 WAYNE — 2 Room Standard',19999,'[{"label": "Total Costing", "amount": 950.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','D-03-26-GES — 2 Room Premium (excl 厨房柜)',21000,'[{"label": "Total Costing", "amount": 1249.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','A-10-06-GES — 2 Room Standard',19999,'[{"label": "Total Costing", "amount": 750.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','A-11-13-WAYNE — 2 Room Standard',18500,'[{"label": "Total Costing", "amount": 1039.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','B-03A-01 WAYNE — 3 Room Premium',29999,'[{"label": "Total Costing", "amount": 1010.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','B-03-05 WAYNE — 3 Room Premium',29999,'[{"label": "Total Costing", "amount": 1010.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','D-07-13 WAYNE — 2 Room Standard',19999,'[{"label": "Total Costing", "amount": 910.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','D-12-11-CHAI — 2 Room Premium',24999,'[{"label": "Total Costing", "amount": 990.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','B-12-02-GES — 3 Room Premium',16000,'[{"label": "Total Costing", "amount": 900.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','reno','B-11-07-CZX',30999,'[{"label": "Total Costing", "amount": 1000.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/008','smarthome','B-08-07 — Smart Home',6000,'[{"label": "Total Costing", "amount": 2375.38}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2602/005-B','smarthome','C-01-02 — Smart Home',6039,'[{"label": "Total Costing", "amount": 2341.19}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/006-CZX','smarthome','B-12-08 — Smart Home',5888,'[{"label": "Total Costing", "amount": 3277.51}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/007-CZX','smarthome','C-05-02 — Smart Home',5388,'[{"label": "Total Costing", "amount": 1802.12}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smarthome','A-11-03 — Smart Home',6039,'[{"label": "Total Costing", "amount": 592.81}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smarthome','C-03-09 — Smart Home',5888,'[{"label": "Total Costing", "amount": 0.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smarthome','E-07-03A — Smart Home',6039,'[{"label": "Total Costing", "amount": 594.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smarthome','C-08-09 — Smart Home',6039,'[{"label": "Total Costing", "amount": 0.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Chatting');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2602/002-GES','smartlock','A-08-33A — Standard Smart Lock',1549,'[{"label": "Total Costing", "amount": 420.98}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/004-LSL','smartlock','D-05-23A — Premium Smart Lock',2149,'[{"label": "Total Costing", "amount": 873.37}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/001-BCY','smartlock','D-07-23 — Premium Smart Lock',2149,'[{"label": "Total Costing", "amount": 680.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smartlock','C-05-02 — Premium Smart Lock',1979,'[{"label": "Total Costing", "amount": 500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2512/003-BCY','smartlock','A-05-03 — Premium Smart Lock',2149,'[{"label": "Total Costing", "amount": 564.47}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smartlock','A-10-06 — Premium Smart Lock',2149,'[{"label": "Total Costing", "amount": 500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smartlock','A-07-06 — Standard Smart Lock',1549,'[{"label": "Total Costing", "amount": 240.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smartlock','B-12-08 — Premium Smart Lock',1899,'[{"label": "Total Costing", "amount": 500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','smartlock','B-08-07 — Premium Smart Lock',2000,'[{"label": "Total Costing", "amount": 0.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/002','smartlock','A-11-03 — Premium Smart Lock',1979,'[{"label": "Total Costing", "amount": 809.37}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/075','alucab','A-10-01 — Small Yard Aluminium Cabinet',2499,'[{"label": "Total Costing", "amount": 1600.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2603/166','alucab','D-08-26 — Dry Kitchen 6ft cabinet',6500,'[{"label": "Total Costing", "amount": 3500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/076','alucab','C-13-12 — Dry Kitchen 7ft cabinet',7000,'[{"label": "Total Costing", "amount": 3750.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','A-10-06 — Plaster Ceiling',4500,'[{"label": "Total Costing", "amount": 2800.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','A-07-06 — Dry and Yard Kitchen Cabinet',11888,'[{"label": "Total Costing", "amount": 8810.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','E-12-05 — Shoes Cabinet',4000,'[{"label": "Total Costing", "amount": 2300.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','A-12-08 — Dry and Yard Kitchen Cabinet',11888,'[{"label": "Total Costing", "amount": 8340.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','B-12-02 — Dry Kitchen Cabinet',12000,'[{"label": "Total Costing", "amount": 0.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','alucab','B-11-07',6000,'[{"label": "Total Costing", "amount": 500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/043','ee','A-10-06',2490,'[{"label": "Total Costing", "amount": 1605.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2603/071','ee','C-13-12',3200,'[{"label": "Total Costing", "amount": 2449.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2603/091','ee','D-01-32',400,'[{"label": "Total Costing", "amount": 316.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2602/065','ee','C-01-02',900,'[{"label": "Total Costing", "amount": 750.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/046','ee','C-03-09',4700,'[{"label": "Total Costing", "amount": 3500.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/177','ee','C-05-02',5500,'[{"label": "Total Costing", "amount": 4000.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/044','ee','E-12-05',6450,'[{"label": "Total Costing", "amount": 4685.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/047','ee','D-03-26',4340,'[{"label": "Total Costing", "amount": 2760.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/182','ee','A-07-06',815,'[{"label": "Total Costing", "amount": 530.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/084','ee','A-10-06 (Kang)',672,'[{"label": "Total Costing", "amount": 360.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2602/117','product','A-03-02',7020,'[{"label": "Total Costing", "amount": 5271.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/047','product','D-03-26',780,'[{"label": "Total Costing", "amount": 640.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/084','product','A-10-06 — Fans',1820,'[{"label": "Total Costing", "amount": 1424.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2606/018','product','E-12-05 — Fans',995,'[{"label": "Total Costing", "amount": 800.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','product','D-03-26 — Fans/aircond',5380,'[{"label": "Total Costing", "amount": 4225.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/043','product','A-10-06 — Fans/aircond',5010,'[{"label": "Total Costing", "amount": 3907.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2606/018','product','E-12-05 — Fans',6040,'[{"label": "Total Costing", "amount": 4682.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/084','product','A-10-06 — Aircond',322,'[{"label": "Total Costing", "amount": 174.3}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2606/018','product','E-12-05 — Aircond',430,'[{"label": "Total Costing", "amount": 242.3}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('','product','D-03-26 — INS AC',1500,'[{"label": "Total Costing", "amount": 780.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Collecting Money');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/043','product','A-10-06 — INS AC',1500,'[{"label": "Total Costing", "amount": 795.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2606/018','product','E-12-05 — INS AC',2000,'[{"label": "Total Costing", "amount": 1134.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2606/018','product','E-12-05 — LIVINOX',3088,'[{"label": "Total Costing", "amount": 2535.65}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2605/084','product','A-10-06 — LIVINOX',550,'[{"label": "Total Costing", "amount": 372.0}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status) values ('CS2604/203','product','A-03-02 — LIVINOX',1830,'[{"label": "Total Costing", "amount": 1477.75}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed');
