-- ============================================================================
--  Full import of costings from Tenn_MindHome_EE_TFM_ALC Status.xlsx
--  (Drive copy modified 11 Jun 2026). Every workbook cost column becomes its
--  own cost line (bank charges, salesman comms, etc.) so the spreadsheet view
--  shows the same columns as the original. Sharing columns are stored as % of
--  gross profit (Mindhome: Other Sharing 50% + CZX & GES 10%; Smart Home /
--  Smart Lock: P.Sharing 50%; Products: Sharing 20%). Suppliers and remarks
--  are in notes. Boss-only table; run in the SQL Editor (service role).
-- ============================================================================

-- Reimport: clears the table first, then inserts (removes ALL costings,
-- including any added/edited by hand).
delete from public.costings;

-- ---- reno (23 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/012','reno','AG15-WAYNE — 2 Room Premium',23444,'[{"label": "Bank Installment Charges", "amount": 2144.4}, {"label": "Bank Charges", "amount": 39.0}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}, {"label": "Material Costing", "amount": 12149.18}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Collecting Money','29/5 settling',now() - interval '0 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/013','reno','AG16-WAYNE — 2 Room Premium',23444,'[{"label": "Bank Installment Charges", "amount": 2144.0}, {"label": "Bank Charges", "amount": 39.0}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}, {"label": "Material Costing", "amount": 11870.31}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','Left backend',now() - interval '1 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/203 8/5/2026','reno','A-03-02-TSL — 2 Room Customize',29999,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 350}, {"label": "Salesman Comm (angel/sally)", "amount": 175}, {"label": "Salesman Comm (CZX/GES)", "amount": 375}, {"label": "Material Costing", "amount": 10838.1}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','',now() - interval '2 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/134','reno','A-08-10-WAYNE — 2 Room Customize',1199,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 250}, {"label": "Material Costing", "amount": 718.53}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','',now() - interval '3 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/202 8/5/26','reno','A-10-01-GES — 2 Room Customize',10238,'[{"label": "Bank Charges", "amount": 98.51}, {"label": "Salesman Comm (w/c/l/g)", "amount": 467}, {"label": "Salesman Comm (angel/sally)", "amount": 100}, {"label": "Salesman Comm (CZX/GES)", "amount": 333}, {"label": "Material Costing", "amount": 5348.56}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','',now() - interval '4 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/061','reno','D-02-32-CHAI — 2 Room Standard',19999,'[{"label": "Bank Charges", "amount": 1139.0}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}, {"label": "Material Costing", "amount": 9224.53}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','9 Jun Done Payment',now() - interval '5 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/123','reno','A-08-32-WAYNE — 2 Room Premium (excl 旋转桌)',21499,'[{"label": "Bank Installment Charges", "amount": 1949.9}, {"label": "Bank Charges", "amount": 39.0}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}, {"label": "Material Costing", "amount": 11352.06}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','',now() - interval '6 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/194','reno','B-12-08-CHAI — 3 Room Premium add-on 厨房吊柜',30699,'[{"label": "Bank Charges", "amount": 160.0}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}, {"label": "Material Costing", "amount": 12713.41}]'::jsonb,'[]'::jsonb,'[{"name": "Other Sharing", "percent": 50}, {"name": "CZX & GES", "percent": 10}]'::jsonb,'Completed','',now() - interval '7 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','A-09-15 BCY — Black Dry Kitchen Cabinet set',9599,'[{"label": "Bank Charges", "amount": 735.29}, {"label": "Material Costing", "amount": 4123.63}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','',now() - interval '8 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','B-03-07 WAYNE — 3 Room Premium 餐边柜 change 厨房吊柜',29999,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Collecting Money','29/5 settling',now() - interval '9 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','C-03-09 BILLY — 3 Room Premium',36999,'[{"label": "Comm Bal", "amount": 550}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}, {"label": "Salesman Comm (angel/sally)", "amount": 200}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Installing','2 June install',now() - interval '10 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','C-05-02 CZX — 3 Room Premium',29999,'[{"label": "Bank Charges", "amount": 160}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Installing','done by 29 June',now() - interval '11 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','E-12-05-GES — 3 Room Premium 餐边柜+玄关柜 change to 厨房对面柜',29999,'[{"label": "Bank Charges", "amount": 39}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','开着料',now() - interval '12 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','D-G-16 WAYNE — 2 Room Standard',19999,'[{"label": "Bank Charges", "amount": 50}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','开着料',now() - interval '13 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','D-03-26-GES — 2 Room Premium (excl 厨房柜)',21000,'[{"label": "Bank Charges", "amount": 349}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','开着料',now() - interval '14 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','A-10-06-GES — 2 Room Standard',19999,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 750}, {"label": "Salesman Comm (angel/sally)", "amount": 150}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '15 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','A-11-13-WAYNE — 2 Room Standard',18500,'[{"label": "Bank Charges", "amount": 1039.0}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '16 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','B-03A-01 WAYNE — 3 Room Premium',29999,'[{"label": "Bank Charges", "amount": 10}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '17 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','B-03-05 WAYNE — 3 Room Premium',29999,'[{"label": "Bank Charges", "amount": 10}, {"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '18 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','D-07-13 WAYNE — 2 Room Standard',19999,'[{"label": "Bank Charges", "amount": 10}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '19 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','D-12-11-CHAI — 2 Room Premium',24999,'[{"label": "Bank Charges", "amount": 90}, {"label": "Salesman Comm (w/c/l/g)", "amount": 900}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','',now() - interval '20 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','B-12-02-GES — 3 Room Premium Masterroom + second bedroom, foyer and tv',16000,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 900}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Chatting','',now() - interval '21 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','reno','B-11-07-CZX',30999,'[{"label": "Salesman Comm (w/c/l/g)", "amount": 1000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Chatting','',now() - interval '22 minutes');

-- ---- smarthome (8 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/008-KKIC 19/5/2026','smarthome','B-08-07 — Smart Home',6000,'[{"label": "Material Costing", "amount": 1955.38}, {"label": "Salesman Comm", "amount": 300}, {"label": "Overriding Comm", "amount": 120}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed','Full Cash · comm release 20/5/2026',now() - interval '23 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2602/005-B 19/5/2026','smarthome','C-01-02 — Smart Home',6039,'[{"label": "Bank Interest", "amount": 594.0}, {"label": "Material Costing", "amount": 1326.41}, {"label": "Salesman Comm", "amount": 300}, {"label": "Overriding Comm", "amount": 120.78}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing','99+(5940) 24 months installment · comm release 20/5/2026',now() - interval '24 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/006-CZX','smarthome','B-12-08 — Smart Home',5888,'[{"label": "Material Costing", "amount": 3159.75}, {"label": "Overriding Comm", "amount": 117.76}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing','50% cash payment only · comm release 20/5/2026',now() - interval '25 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/007-CZX','smarthome','C-05-02 — Smart Home',5388,'[{"label": "Material Costing", "amount": 1694.36}, {"label": "Overriding Comm", "amount": 107.76}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Installing','Full Cash · comm release 20/5/2026',now() - interval '26 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smarthome','A-11-03 — Smart Home',6039,'[{"label": "Bank Interest", "amount": 592.81}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','99+(5940) 36 months installment',now() - interval '27 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smarthome','C-03-09 — Smart Home',5888,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Installing','Pay from Tenn Mindhome',now() - interval '28 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smarthome','E-07-03A — Smart Home',6039,'[{"label": "Bank Interest", "amount": 594.0}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','99 (planning installment)',now() - interval '29 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smarthome','C-08-09 — Smart Home',6039,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Chatting','No contact yet · 3/6 receive payment',now() - interval '30 minutes');

-- ---- smartlock (10 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2602/002-GES','smartlock','A-08-33A — Standard Smart Lock',1549,'[{"label": "Device Costing", "amount": 240}, {"label": "Installation", "amount": 150}, {"label": "Salesman Comm (3%)", "amount": 30.98}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed','',now() - interval '31 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/004-LSL','smartlock','D-05-23A — Premium Smart Lock',2149,'[{"label": "Device Costing", "amount": 500}, {"label": "Installation", "amount": 180}, {"label": "Lalamove", "amount": 128.9}, {"label": "Salesman Comm (3%)", "amount": 64.47}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'Completed','',now() - interval '32 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/001-BCY','smartlock','D-07-23 — Premium Smart Lock',2149,'[{"label": "Device Costing", "amount": 500}, {"label": "Installation", "amount": 180}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','',now() - interval '33 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smartlock','C-05-02 — Premium Smart Lock',1979,'[{"label": "Device Costing", "amount": 500}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','After finish Reno · grey (stock)',now() - interval '34 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2512/003-BCY','smartlock','A-05-03 — Premium Smart Lock',2149,'[{"label": "Device Costing", "amount": 500}, {"label": "Salesman Comm (3%)", "amount": 64.47}]'::jsonb,'[]'::jsonb,'[{"name": "P.Sharing", "percent": 50}]'::jsonb,'In Progress','After finish Reno · black (order)',now() - interval '35 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smartlock','A-10-06 — Premium Smart Lock',2149,'[{"label": "Device Costing", "amount": 500}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','After finish Reno · black (stock)',now() - interval '36 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smartlock','A-07-06 — Standard Smart Lock',1549,'[{"label": "Device Costing", "amount": 240}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','After finish Reno · normal (stock)',now() - interval '37 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smartlock','B-12-08 — Premium Smart Lock',1899,'[{"label": "Device Costing", "amount": 500}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','After finish Reno · black (order)',now() - interval '38 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','smartlock','B-08-07 — Premium Smart Lock',2000,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Collecting Money','Planning install · black (stock)',now() - interval '39 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/002','smartlock','A-11-03 — Premium Smart Lock',1979,'[{"label": "Bank Comm", "amount": 19.79}, {"label": "Device Costing", "amount": 500}, {"label": "Installation", "amount": 250}, {"label": "Salesman Comm (3%)", "amount": 59.37}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Black (stock)',now() - interval '40 minutes');

-- ---- alucab (9 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/075 8/5/2026','alucab','A-10-01 — Small Yard Aluminium Cabinet',2499,'[{"label": "Cabinet Costing", "amount": 1600}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Classic Home',now() - interval '41 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2603/166 8/5/26','alucab','D-08-26 — Dry Kitchen table top 6ft cabinet',6500,'[{"label": "Cabinet Costing", "amount": 3250}, {"label": "Sink & Paip", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Cabinet: Classic Home · Sink & Paip: Tenn Fasteners',now() - interval '42 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/076 8/5/26','alucab','C-13-12 — Dry Kitchen table top 7ft cabinet',7000,'[{"label": "Cabinet Costing", "amount": 3500}, {"label": "Sink & Paip", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Cabinet: Classic Home · Sink & Paip: Tenn Fasteners',now() - interval '43 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','A-10-06 — Plaster Ceiling',4500,'[{"label": "Cabinet Costing", "amount": 2800}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Classic Home',now() - interval '44 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','A-07-06 — Dry and Yard Kitchen Cabinet',11888,'[{"label": "Cabinet Costing", "amount": 8560}, {"label": "Sink & Paip", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Installing','Cabinet: Classic Home · Sink & Paip: Tenn Fasteners · Ask Lee Qing for date install · passed key to them ard',now() - interval '45 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','E-12-05 — Shoes Cabinet',4000,'[{"label": "Cabinet Costing", "amount": 2300}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Classic Home · Ask Lee Qing for date install',now() - interval '46 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','A-12-08 — Dry and Yard Kitchen Cabinet',11888,'[{"label": "Cabinet Costing", "amount": 8090}, {"label": "Sink & Paip", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Installing','Cabinet: Classic Home · Sink & Paip: Tenn Fasteners · Waiting owner pass gas stove to office',now() - interval '47 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','B-12-02 — Dry Kitchen Cabinet',12000,'[{"label": "Sink & Paip", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Chatting','Cabinet: Classic Home · Sink & Paip: Tenn Fasteners',now() - interval '48 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','alucab','B-11-07',6000,'[{"label": "Sink & Paip", "amount": 500}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Chatting','',now() - interval '49 minutes');

-- ---- ee (11 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/043 8/5/26','ee','A-10-06 — EE',2490,'[{"label": "Costing", "amount": 1605}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Seng',now() - interval '50 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2603/071 / CS2603/138 8/5/26','ee','C-13-12 — EE',3200,'[{"label": "Costing", "amount": 2449}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Seng',now() - interval '51 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2603/091 8/5/26','ee','D-01-32 — EE',400,'[{"label": "Costing", "amount": 316}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Seng',now() - interval '52 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2602/065 8/5/26','ee','C-01-02 — EE',900,'[{"label": "Costing", "amount": 750}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kwan · Due to high profit in Smart Home so price lower',now() - interval '53 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/046 8/5/26','ee','C-03-09 — EE',4700,'[{"label": "Costing", "amount": 3500}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kwan',now() - interval '54 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/177 8/5/2026','ee','C-05-02 — EE',5500,'[{"label": "Costing", "amount": 4000}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kwan',now() - interval '55 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/044 8/5/2026','ee','E-12-05 — EE',6450,'[{"label": "Costing", "amount": 4685}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kang',now() - interval '56 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/047 8/5/26','ee','D-03-26 — EE',4340,'[{"label": "Costing", "amount": 2760}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Collecting Money','Supplier: Kang · Collected 80%',now() - interval '57 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','ee','B-12-08 — Change Plug Location',0,'[{"label": "Costing", "amount": 250}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kang · charge Mindhome costing',now() - interval '58 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/182 25/5/2026','ee','A-07-06 — EE',815,'[{"label": "Costing", "amount": 530}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kang',now() - interval '59 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/084 14/5/2026','ee','A-10-06 — EE',672,'[{"label": "Costing", "amount": 360}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Kang',now() - interval '60 minutes');

-- ---- product (15 rows) ----
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2602/117','product','A-03-02 — Products',7020,'[{"label": "Costing", "amount": 5271}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Teck Trading',now() - interval '61 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/047','product','D-03-26 — Products',780,'[{"label": "Costing", "amount": 640}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Teck Trading',now() - interval '62 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/084 14/5/26','product','A-10-06 — Products',1820,'[{"label": "Costing", "amount": 1424}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Teck Trading',now() - interval '63 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2606/018','product','E-12-05 — Products',995,'[{"label": "Costing", "amount": 800}]'::jsonb,'[]'::jsonb,'[{"name": "Sharing", "percent": 20}]'::jsonb,'Completed','Supplier: Teck Trading',now() - interval '64 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','product','D-03-26 — Products',5380,'[{"label": "Costing", "amount": 4225}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Collecting Money','Supplier: Teck Trading · 28/5/2026 install',now() - interval '65 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/043 08/5/26','product','A-10-06 — Products',5010,'[{"label": "Costing", "amount": 3907}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'In Progress','Supplier: Teck Trading · 28/5/2026 install',now() - interval '66 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2606/018','product','E-12-05 — Products',6040,'[{"label": "Costing", "amount": 4682}]'::jsonb,'[]'::jsonb,'[{"name": "Sharing", "percent": 20}]'::jsonb,'Completed','Supplier: Teck Trading · 28/5/2026 install',now() - interval '67 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/084 14/5/26','product','A-10-06 — Lighting',322,'[{"label": "Costing", "amount": 174.3}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Tyng Lighning',now() - interval '68 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2606/018','product','E-12-05 — Lighting',430,'[{"label": "Costing", "amount": 242.3}]'::jsonb,'[]'::jsonb,'[{"name": "Sharing", "percent": 20}]'::jsonb,'Completed','Supplier: Tyng Lighning',now() - interval '69 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('','product','D-03-26 — INS AC',1500,'[{"label": "Costing", "amount": 780}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Collecting Money','Supplier: Ah Yong · 28/5/2026 install',now() - interval '70 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/043','product','A-10-06 — INS AC',1500,'[{"label": "Costing", "amount": 795}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: Ah Yong · 28/5/2026 install',now() - interval '71 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2606/018','product','E-12-05 — INS AC',2000,'[{"label": "Costing", "amount": 1134}]'::jsonb,'[]'::jsonb,'[{"name": "Sharing", "percent": 20}]'::jsonb,'Completed','Supplier: Ah Yong · 28/5/2026 install',now() - interval '72 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2606/018','product','E-12-05 — LIVINOX',3088,'[{"label": "Costing", "amount": 2535.65}]'::jsonb,'[]'::jsonb,'[{"name": "Sharing", "percent": 20}]'::jsonb,'Installing','Supplier: LIVINOX · Waiting MindHome cabinet tgt',now() - interval '73 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2605/084 14/05/26','product','A-10-06 — LIVINOX',550,'[{"label": "Costing", "amount": 372}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: LIVINOX',now() - interval '74 minutes');
insert into public.costings (cash_sale_no, category, customer, revenue, costs, commissions, shares, status, notes, created_at) values ('CS2604/203','product','A-03-02 — LIVINOX',1830,'[{"label": "Costing", "amount": 1477.75}]'::jsonb,'[]'::jsonb,'[]'::jsonb,'Completed','Supplier: LIVINOX',now() - interval '75 minutes');

-- 76 rows imported.
